from . import appraisal
from . import res_config_settings
from . import res_company
from . import appraisal_note
from . import appraisal_goal
from . import hr_employee
from . import hr_department
from . import calendar_event
from . import hr_appraisal_goal_tag
from . import survey